### ISSUE TITLE
Windows Universal App IoT Core Support

### ISSUE THREAD

**Issue by sidhant** [Code-Sharp/WampSharp-docs#1]
Unable to integrate WampSharp into my IoT UWP apps that make use of .NET 5.0. Error as follows when installing package:

```
Install-Package : Version conflict detected for System.Collections.Immutable. 
 CrossBarTest (≥ 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (≥ 5.0.0) -> Microsoft.NETCore (≥ 5.0.0) -> 
System.Collections.Immutable (≥ 1.1.37) 
 CrossBarTest (≥ 1.0.0) -> WampSharp.Default (≥ 1.2.3.12-beta) -> WampSharp.Default.Client (= 1.2.3.12-beta) -> 
WampSharp.NewtonsoftJson (= 1.2.3.12-beta) -> WampSharp (= 1.2.3.12-beta) -> System.Collections.Immutable (= 1.1.36).
At line:1 char:1
+ Install-Package WampSharp.Default -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Install-Package : Version conflict detected for System.Collections.Immutable. 
 CrossBarTest (≥ 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (≥ 5.0.0) -> Microsoft.NETCore (≥ 5.0.0) -> 
System.Collections.Immutable (≥ 1.1.37) 
 CrossBarTest (≥ 1.0.0) -> WampSharp.Default (≥ 1.2.3.12-beta) -> WampSharp.Default.Client (= 1.2.3.12-beta) -> 
WampSharp.Windows (= 1.2.3.12-beta) -> WampSharp (= 1.2.3.12-beta) -> System.Collections.Immutable (= 1.1.36).
At line:1 char:1
+ Install-Package WampSharp.Default -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

```

**Comment by darkl** [comment]
I'm not sure about the platforms, but .NET Core support is on the roadmap. I'm not sure it is needed for UWP though. If you can reference me to some documentation about this it might help me understand what is actually missing.

**Comment by sidhant** [comment]
The key issue that is preventing me from integrating this is Wamp#'s current dependence on version 1.1.36 of System.Collections.Immutable; while the IoT core extension prefers 1.1.37. The issue may be as simple as resolving this.

**Comment by darkl** [comment]
It seems not to be so simple, since for .NET40 I use Rackspace.Collections.Immutable and this one is equivalent to 1.1.36 (Doesn't have a 1.1.37 version yet). Might investigate this further during the weekend.

**Comment by sidhant** [comment]
Thank you! Looking forward to a fix! I am basically trying to include this on an app that runs on the Raspberry Pi 2.

**Comment by darkl** [comment]
Hi,
I'm sorry but I can't manage making my continuous integration to work with System.Collections.Immutable 1.1.37. I can suggest you to manually compile WampSharpPortable.sln on your machine and manually reference the compiled sources, until I sort this out.

**Comment by sharwell** [comment]
You should be able to use an assembly binding redirect for this. The assembly versioning policy used by System.Collections.Immutable requires the use of assembly binding redirection for patch releases (e.g. 1.1.36 &rarr; 1.1.37).

**Comment by darkl** [comment]
Ok, I managed to make continuous integration work thanks to [this answer](http://stackoverflow.com/a/32361847).

Please try now the develop version.

In order to try it, you need to add a package source to https://www.myget.org/F/wampsharp/api/v2 (Tools -> NuGet Package Manager -> Package Manager Settings -> Packages Sources -> + button)

**Comment by darkl** [comment]
@sidhant, have you managed to try this develop version?

**Comment by sidhant** [comment]
@darkl not yet :( I had to ship that project off for a demo. Will give it a try this weekend for the next sprint when I improve it with WAMP messaging. Thank you for actually working on it so quickly! Really appreciate all your effort. If this works out, I am looking forward to recommending more folks around me working on WinIOT to give this a shot.

**Comment by sidhant** [comment]
@darkl Just gave it a try, works great!! THANK YOU!

**Comment by darkl** [comment]
WampSharp v1.2.4.18-beta is now available with .NET Standard 1.3 support.
