### ISSUE TITLE
Where can I ask questions about WampSharp?

### ISSUE THREAD

**Issue by Eternal21** [Code-Sharp/WampSharp-docs#2]
Hi.  Apologies if this is the wrong place to post, but I couldn't find anything in documentation on where to ask WampSharp specific questions.  I did post on stackoverflow, but there are only 10 WampSharp-related tags on there, so I figured I'll try on here as well.  Here's my question:

'How to send a message to a specific client using WampSharp?'

http://stackoverflow.com/questions/35700030/how-to-send-a-message-to-a-specific-client-using-wampsharp

@darkl

**Comment by darkl** [comment]
Hi @Eternal21,
I've answered your question on StackOverflow.

WampSharp doesn't have any mailing list nor a chat channel nowadays. Currently most questions are asked via issues on the GitHub project site. I was thinking about creating a Google groups mailing list or a Gitter.im channel, but I'm not sure it is necessary.

Best regards
Elad

**Comment by Eternal21** [comment]
Thanks.  As per your recommendation, I'll be using GitHub project site to ask questions from now on:
https://github.com/Code-Sharp/WampSharp/issues
