### ISSUE TITLE
can't get your subscriber example to work

### ISSUE THREAD

**Issue by sabazk** [Code-Sharp/WampSharp-docs#6]
Using the code below

Linux OpenSuSe Tumbleweed / mono 4.4.2 /nuget Latest/WampSharp 1.2.5-beta/target net45

DefaultWampChannelFactory doesn't seem to exist in WampSharp as imported on Linux
IWampChannel channel =
                factory.CreateJsonChannel(serverAddress, "realm1");
Seems that CreateJsonChannel doesn't exist either

Any Help would be appreciated

```
using System;
using System.Reactive.Linq;
using System.Reactive.Subjects;
using System.Threading.Tasks;
using WampSharp.V2;
using WampSharp.V2.Client;


namespace Wamp
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            DefaultWampChannelFactory factory =
                new DefaultWampChannelFactory();

            const string serverAddress = "wss://api.poloniex.com";

            IWampChannel channel =
                factory.CreateJsonChannel(serverAddress, "realm1");

            channel.Open().Wait(5000);

            IWampRealmProxy realmProxy = channel.RealmProxy;

            int received = 0;
            IDisposable subscription = null;

            subscription =
                realmProxy.Services.GetSubject<int>("BTC_XMR")
                    .Subscribe(x =>
                        {
                            Console.WriteLine("Got Event: " + x);

                            received++;

                            if (received > 5)
                            {
                                Console.WriteLine("Closing ..");
                                subscription.Dispose();
                            }
                        });

            Console.ReadLine();
        }
    }
}
```

**Comment by darkl** [comment]
Please install WampSharp.WebSocket4Net (remove WampSharp.WebSockets) and use
fluent syntax instead. See [here](https://github.com/Code-Sharp/WampSharp-docs/blob/master/WAMP2/Client/WampChannel.md#fluent-syntax).

Elad

**Comment by sabazk** [comment]
Thanks for pointing me in the right direction! Got it.

**Comment by ronki2304** [comment]
hello thank you for this help too 
I have the same environment but I have another problem :  

> Could not load type of field 'WampSharp.Newtonsoft.DetailsOptionsConverter:mTypeToConstructor' (1) due to: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:<unknown type> member:<none>

Both reference WampSharp.NewtonSoft and System.collection.imutable are present

Any idea ?

thank you in advance
